
# This file is automatically generated, you probably don't want to edit this

termfrequencyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "termfrequencyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            fretext = NULL, ...) {

            super$initialize(
                package="termfrequency",
                name="termfrequency",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..fretext <- jmvcore::OptionVariable$new(
                "fretext",
                fretext)

            self$.addOption(private$..dep)
            self$.addOption(private$..fretext)
        }),
    active = list(
        dep = function() private$..dep$value,
        fretext = function() private$..fretext$value),
    private = list(
        ..dep = NA,
        ..fretext = NA)
)

termfrequencyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "termfrequencyResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Term Frequency")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Term Frequency"))}))

termfrequencyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "termfrequencyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "termfrequency",
                name = "termfrequency",
                version = c(1,0,0),
                options = options,
                results = termfrequencyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Term Frequency
#'
#' 
#' @param data .
#' @param dep .
#' @param fretext .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
termfrequency <- function(
    data,
    dep,
    fretext) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("termfrequency requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(fretext)) fretext <- jmvcore::resolveQuo(jmvcore::enquo(fretext))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(fretext), fretext, NULL))


    options <- termfrequencyOptions$new(
        dep = dep,
        fretext = fretext)

    analysis <- termfrequencyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

